name: gradient_cached_image
description: A new Flutter package project.
version: 0.1.1
author: Shun Kakinoki <shunkakinoki@gmail.com>
homepage: https://github.com/shunkakinoki/gradient_cached_image

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
